// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"es_CO": &dictionary{index: es_COIndex, data: es_COData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%d books available\n": 1,
	"Welcome!\n":           0,
}

var en_GBIndex = []uint32{ // 3 elements
	0x00000000, 0x0000000e, 0x00000046,
} // Size: 36 bytes

const en_GBData string = "" + // Size: 70 bytes
	"\x04\x00\x01\x0a\x09\x02Welcome!\x04\x00\x01\x0a3\x14\x01\x81\x01\x00=" +
	"\x01\x13\x02One book available\x00\x16\x02%[1]d books available"

var es_COIndex = []uint32{ // 3 elements
	0x00000000, 0x00000011, 0x0000004d,
} // Size: 36 bytes

const es_COData string = "" + // Size: 77 bytes
	"\x04\x00\x01\x0a\x0c\x02Bienvenido!\x04\x00\x01\x0a7\x14\x01\x81\x01\x00" +
	"=\x01\x14\x02Un libro disponible\x00\x19\x02%[1]d libros disponibles"

	// Total table size 219 bytes (0KiB); checksum: 4CC762B1
